### PR TITLE
Footer Links Open New Tab

### PR DESCRIPTION
**Pull request by avi-l**
https://github.com/amlan-roy/resume-craft/issues/29

# Summary
Open Footer Links in New Tab
## Changes made:
add target="_blank" to <Link> component in Footer

## How Has This Been Tested?
Ran locally, tested links do pop open in new tab

https://github.com/amlan-roy/resume-craft/assets/68050609/bf05871f-a5ea-45de-90c0-7bcc0c9d832a

### CODE REVIEW

**Review by amlan-roy — APPROVED** [review]
Thanks. LGTM!

**Review by amlan-roy — CHANGES_REQUESTED** [review]
Snapshots needs to be updated. Can merge the PR after the snapshots have been updated.

**Comment by avi-l** [comment]
screen recording added to PR summary.

**Comment by amlan-roy** [comment]
> Snapshots needs to be updated. Can merge the PR after the snapshots have been updated.

@avi-l : Running the command `npm run test -- -u` will update the jest snapshots. Once the snapshots are updated, the existing tests will pass.
We can then merge this PR to master.

**Comment by avi-l** [comment]
ha, ok sorry, I misunderstood for what you were asking.. standby...

**Comment by amlan-roy** [comment]
> ha, ok sorry, I misunderstood for what you were asking.. standby...

No worries. Thanks for the effort. Merging this PR 🚀

**Review by amlan-roy — APPROVED** [review]

**Pull request merged**
